### ISSUE TITLE
не всякий lessc выводит результат в stdout

### ISSUE THREAD

**Issue by unel** [andreyfedoseev/django-less#1]
мне попался какой-то странный lessc, который выводил результат обратно в файл, эта ситуация никак не обрабатывается

**Comment by andreyfedoseev** [comment]
Я использую lessc, который можно установить, следуя инструкциям на официальном сайте http://lesscss.org/

Какой lessc используете вы?

**Comment by unel** [comment]
если честно, не знаю (он уже был установлен на хостинге), но судя по расположению исполняемого файла в /var/lib/gems/1.8/bin/lessc - это какой-то его аналог на ruby

**Comment by andreyfedoseev** [comment]
В таком случае рекомендую поставить официальную версию. Вы можете указать полный пусть к исполняемому файлу lessc используя настройку LESS_EXECUTABLE в settings.py

**Comment by unel** [comment]
к сожалению, официальную версию поставить не имею возможности)
в локальном каталоге я модифицировал поведение less.py, чтобы она читала файл, просто решил уведомить о такой ситуации)

**Comment by andreyfedoseev** [comment]
К сожалению я вряд ли смогу программно определить, какая именно версия используется в системе чтобы скорректировать поведение less.py.

Проверьте, может быть ваша версия lessc имеет какой-то параметр, который позволяет выводить результат в stdout. Если это так, то попробуйте указать этот ключ в параметре LESS_EXECUTABLE.
