### ISSUE TITLE
Unable to serve in development mode

### ISSUE THREAD

**Issue by EugeneDae** [andreyfedoseev/django-less#11]
I'm using Django 1.4.3 in development mode. 

The structure of my project:

```
project/
    manage.py
    core/
        settings.py
        static/
            less-cache/ <---- I want LESS cache to go here
            admin/
                less/
                    base.less <---- the file I want to compile
        ...
```

_settings.py_

```
STATIC_ROOT = ''
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    PROJECT_PATH + '/static/',
)
LESS_OUTPUT_DIR = 'core/static/less-cache/'
```

("core" is the name of my main application with settings.py).

If I do not specify LESS_OUTPUT_DIR, Django-Less generates LESS_CACHE in the root of my project (and not media root, as docs say...) so I have to point it to my actual static folder using LESS_OUTPUT_DIR.

The problem is:

`<link rel="stylesheet" href="{{ STATIC_URL }}{% less "admin/less/base.less" %}" />`

turns into

`<link rel="stylesheet" href="/static/core/static/less-cache/admin/less/base-6792ecdf72ee.css" />`

It gives 404, because in my case the URL should not contain the "core/static" part.

I'm not very experienced with static/media serving in Django (I just picked up those settings from one of the StackOverflow posts), but in my understanding if Django-Less offered a separate setting for URL path, I could easily solve my problem.

**Comment by andreyfedoseev** [comment]
Switch to django-less==0.6 and try the following settings:

```
LESS_ROOT = os.path.join(os.path.dirname(__file__), "static")  # project/core/static/
LESS_OUTPUT_DIR = "less-cache"
STATICFILES_DIRS = (
    LESS_ROOT,
)
```
