### ISSUE TITLE
problems with includes in .less files

### ISSUE THREAD

**Issue by l00mi** [andreyfedoseev/django-less#2]
I like the idea of your plugin. It is small and unobtrusive, exactly what I need. The only problem I experience is that lessc can not follow included less files like the ones which are coming with bootstrap. 

```
at /var/lib/gems/1.8/gems/less-2.2.1/lib/less/js/lib/less/parser.js:390:69: 'bootstrap/bootstrap.less' wasn't found. (Less::ParseError)
    from /var/lib/gems/1.8/gems/less-2.2.1/lib/less/parser.rb:57:in `to_css'
    from /var/lib/gems/1.8/gems/less-2.2.1/lib/less/java_script/v8_context.rb:90:in `do_lock'
    from /var/lib/gems/1.8/gems/less-2.2.1/lib/less/java_script/v8_context.rb:88:in `do_lock'
    from /var/lib/gems/1.8/gems/less-2.2.1/lib/less/java_script/v8_context.rb:60:in `lock'
    from /var/lib/gems/1.8/gems/less-2.2.1/lib/less/java_script/v8_context.rb:30:in `exec'
    from /var/lib/gems/1.8/gems/less-2.2.1/lib/less/java_script.rb:26:in `exec'    from /var/lib/gems/1.8/gems/less-2.2.1/lib/less/parser.rb:57:in `to_css'
    from /var/lib/gems/1.8/gems/less-2.2.1/bin/lessc:23
    from /usr/local/bin/lessc:19:in `load'
    from /usr/local/bin/lessc:19
```

Is there an easy remedy for this problem?

**Comment by andreyfedoseev** [comment]
Please show how you use the template tag in your template.

What is the value of STATIC_ROOT / MEDIA_ROOT settings? Where is the bootstrap/bootstrap.less located?

**Comment by l00mi** [comment]
My setup is the following ...

`STATIC_ROOT = '/srv/www/website/static/'`
`STATIC_URL = '/static/'`

in static/less/ is style.less with `import "bootstrap/bootstrap.less";`
and this bootstrap.less is located in static/less/bootstrap/bootstrap.less

And finaly my template contains the following line
`<link rel="stylesheet/less" href="{{ STATIC_URL }}{% less "less/style.less" %}" />`

The file is found as I can tell from the error which speaks about the file `bootstrap/bootstrap.less` which only is referred to in style.less.

**Comment by andreyfedoseev** [comment]
It works for me. I've added a test to check this: https://github.com/andreyfedoseev/django-less/commit/b74299d3e9af55955aae883fa06a47f39453f929
