### ISSUE TITLE
Usage on Mac OS X

### ISSUE THREAD

**Issue by luyzdeleon** [andreyfedoseev/django-less#24]
Hello,

I am trying to use the template tag for a django application and while trying to setup my development environment on Mac OS X, the less tag is failing with:

[OS Error] No such file or directory

For my less file, which is on the directory i am indicating.
The issue is on line 47 of the less.py file.

**Comment by andreyfedoseev** [comment]
Hello, 

This package is not maintained anymore, please try [django-static-precompiler](https://github.com/andreyfedoseev/django-static-precompiler) (which is compatible with django-less) and open an issue there if necessary. Thanks.
