### ISSUE TITLE
Compiled css file not found

### ISSUE THREAD

**Issue by schmittlauch** [andreyfedoseev/django-less#9]
I want to include an external less file. I followed the instructions from your README and the css file is created in the LESS_CACHE folder and visible in the filesystem, but the django development server replies with a **404 - Not Found**

This is my project: https://github.com/schmittlauch/chorplaner/tree/less
- the template where I want to use the less file is chor/templates/base.css

**Comment by schmittlauch** [comment]
I'm in development mode and the LESS_CACHE folder is created in the staticfiles folder as well as the compiled css files. But nevertheless a 404 rises

**Comment by andreyfedoseev** [comment]
@schmittlauch I've fixed that in v0.6 and sent a pull request to your project. Please test it and close the issue if it works now.
